# Generated by Django 4.1.5 on 2023-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0002_appointment_subscribersuser_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
